# build a docker image and push it to the GitHub Container Registry

name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag gitflow-test-gui:${{ github.ref_name }}
      - name: Log in to the Container registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push the latest Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/ioncoder/gitflow-test-gui:latest
      - name: Push the Docker image with the current timestamp
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/ioncoder/gitflow-test-gui:${{ github.ref_name}}