name: Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - run: npx semantic-release
        id: get-next-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "New release version is ${{ steps.release.outputs.new-release-version }}"
        id: release
        if: steps.release.outcome == 'success'
    outputs:
      new-release-version: ${{ steps.release.outputs.new-release-version }}
  build:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag gitflow-test-gui:${{ needs.release.outputs.new-release-version }}
      - name: Log in to the Container registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push the latest Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/ioncoder/gitflow-test-gui:latest
      - name: Push the Docker image with the current ref tag
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/ioncoder/gitflow-test-gui:${{ needs.release.outputs.new-release-version }}